swagger: '2.0'
info:
  title: Cloud Endpoints + App Engine
  description: Sample API on Cloud Endpoints with an App Engine backend
  version: 1.0.0
host: jsonservice-amnbf5pygq-uc.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://individual-project-295303.us-central1.r.appspot.com
  jwt_audience: 650359285904-jj74ael7fsdp4tkgkedcd6k7t6f0vl7k.apps.googleusercontent.com
  protocol: h2
paths:
  /:
    get:
      summary: Greet a user
      operationId: hello
      responses:
        '200':
          description: A successful response
          schema:
            type: string
